### ISSUE TITLE
IGListKitCrashes when used in an iMessages Extension

### ISSUE THREAD

**Issue by ishabazz** [Instagram/IGListKit#77]
## New issue checklist
- [ x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
### General information
- Library version(s):1.0.0
- XCode:8.0
- iOS version(s):10.0.x
- Devices/Simulators affected:iPhone 7Plus
- Reproducible in the demo project? (Yes/No):Yes

Running iMessage Apps which have IGListKit included via CocoaPods results in the app crashing on launch with the error like the following:  dyld: Library not loaded: @rpath/IGListKit.framework/IGListKit
  Referenced from: /Users/demo/Library/Developer/CoreSimulator/Devices/5C343568-A532-405F-8B65-52A049827328/data/Containers/Bundle/Application/AA18B7D3-48C4-4958-A14C-C056A309D6D8/IGListStickerDemo.app/PlugIns/MessagesExtension.appex/MessagesExtension
  Reason: image not found

Check out  https://github.com/ishabazz/IGListKitMessagesExtensionDemo  for a sample project that exhibits this error.

**Comment by rnystrom** [comment]
I've definitely seen this error before, but that was using a non-Swift library in a Swift app using Buck for dep management. Might be something similar though.

**Comment by jessesquires** [comment]
Not clear if this is:

1. a bug in IGListKit
2. a bug in CocoaPods
3. a issue with project setup

**Comment by rnystrom** [comment]
Off the bat I get an Xcode warning in the sample project:

> ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/rnystrom/Library/Developer/Xcode/DerivedData/IGListStickerDemo-cherwvpgwwdqmjhkvyhkxnqnciyx/Build/Products/Debug-iphonesimulator/IGListKit/IGListKit.framework/IGListKit

**Comment by rnystrom** [comment]
After `$ pod install` I see some weird CocoaPods warnings:

```
[!] The `IGListStickerDemo [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-IGListStickerDemo/Pods-IGListStickerDemo.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `IGListStickerDemo [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-IGListStickerDemo/Pods-IGListStickerDemo.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by ishabazz** [comment]
Ok.  To recap, you removed it from the Podfile, ran pod install and  manually installed the framework?

**Comment by rnystrom** [comment]
@ishabazz I actually didn't remove it from the Podfile at first, just added to Linked Libraries and Frameworks. Then I built, got compiler errors, removed the framework from Linked Libraries and Frameworks, then did `$ pod install` again. This definitely isn't the answer but might be a clue to what's going on.

**Comment by ishabazz** [comment]
I looked into that initial compiler warning and it leads here https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6

**Comment by rnystrom** [comment]
Fixing the warning in #79

**Comment by rnystrom** [comment]
@ishabazz ok now I can't get it to happen at all anymore. I ran 

```
$ pod deintegrate
$ rm -rf ~/Library/Developer/Xcode/DerivedData
$ pod install
```

It works and installs on multiple simulators and device.

I believe my Podfile is unchanged from what you originally sent:

```
target 'IGListStickerDemo' do
  use_frameworks!
  pod 'IGListKit'
end

target 'MessagesExtension' do
  use_frameworks!
  pod 'IGListKit'
end
```

**Comment by ishabazz** [comment]
hmm...tried that but mine still crashes. Your Podifle is the same as mine

**Comment by rnystrom** [comment]
@ishabazz a couple other configs I tried that seemed to work:

- Remove `IGListKit` from the main target since its empty
- Remove `use_frameworks!`

**Comment by ishabazz** [comment]
Progress!  I can get the demo project to run without crashing.  I get a compiler error when trying "import IGListKit" though.

**Comment by rnystrom** [comment]
@ishabazz any update on this? Not really sure what to do here :/

**Comment by ishabazz** [comment]
Still a problem. Compiles fine until you try to import IGListKit, then doesn't compile and gives a "No such module 'IGListKit' found"  Did it work for you?

**Comment by jessesquires** [comment]
> Compiles fine until you try to import IGListKit, then doesn't compile and gives a "No such module 'IGListKit' found"

Hm... 🤔 Sounds like this is probably a project setup issue... ?

**Comment by Sherlouk** [comment]
Created a very basic example over on my fork ([here](https://github.com/Sherlouk/IGListKit/tree/multiple-schemes)) of an iMessage extension.

I've also downloaded your demo repository and found the issue: In your "Build Phases" tab you have a run action for '[CP] Copy Pods Resources' but not one for '[CP] Embed Pods Frameworks' hence the error.

I will create a pull request on your demo repository with a fix for this! (Added the missing run script)

**Comment by Sherlouk** [comment]
@rnystrom Relating to my previous comment, how would you feel about adding extension examples into this repo? Happy to make modifications/make them more useful!

[my fork](https://github.com/Sherlouk/IGListKit/tree/multiple-schemes) contains an example for both a Today Extension and an iMessage Extension.

**Comment by ishabazz** [comment]
Thanks  @Sherlouk!

**Comment by rnystrom** [comment]
@Sherlouk yes yes yes yes yes! That would be amazing! Should we clean up and add your fork to the example or should we make something new?

**Comment by ishabazz** [comment]
By the way.  When trying to submit the build to TestFlight I ran into this issue  http://stackoverflow.com/questions/40005130/error-itms-90685-cfbundleidentifier-collision-there-is-more-than-one-bundle   

Still working on a resolution

**Comment by jessesquires** [comment]
@ishabazz -- This should be fixed with CocoaPods 1.1

http://blog.cocoapods.org/CocoaPods-1.1.0/

**Comment by Sherlouk** [comment]
@rnystrom @ishabazz Flagging to be closed?

There's now an example in the pack, and the issue at hand was seemingly resolved.

**Comment by jessesquires** [comment]
👍 

will re-open if needed

**Comment by philosopherdog** [comment]
I'm still getting this warning intermittently. I'm using pods 1.6.1. Why is this happening and how do I fix it.
